app/helpers/kmyblue_capabilities_helper.rb
app/serializers/nodeinfo/serializer.rb
spec/serializers/nodeinfo/serializer_spec.rb
spec/serializers/rest/instance_serializer_spec.rb

Fix: #89 NodeInfo向けの機能一覧表を作成して区別

---

app/lib/activitypub/activity/follow.rb
app/models/friend_domain.rb
spec/lib/activitypub/activity/follow_spec.rb
spec/models/friend_domain_spec.rb

Change: #82 フレンド申請時、自分のサーバーのInbox URLを伝える

---

app/controllers/settings/privacy_controller.rb
app/controllers/settings/privacy_extra_controller.rb
app/views/settings/privacy/show.html.haml
app/views/settings/privacy_extra/show.html.haml

Change: #52 購読拒否設定項目を追加設定画面に移動

---

app/javascript/mastodon/actions/bookmark_categories.js
app/javascript/mastodon/features/bookmark_category_statuses/index.jsx

Change: ブックマーク分類のページネーション

---

app/lib/status_reach_finder.rb
app/services/emoji_react_service.rb
spec/services/emoji_react_service_spec.rb

Fix: 他のサーバーの同じ絵文字を複数つけられる問題

---

app/controllers/admin/ng_words_controller.rb
app/lib/activitypub/activity/create.rb
app/models/admin/ng_word.rb
app/models/form/admin_settings.rb
app/views/admin/ng_words/show.html.haml
config/locales/en.yml
config/locales/ja.yml
spec/lib/activitypub/activity/create_spec.rb

Add: #43 フォローしていないアカウントからのリプライのNGワード

---

app/javascript/mastodon/components/status.jsx

Change: #93 引用投稿よりも添付画像を先に表示

---

app/javascript/mastodon/actions/circles.js
app/javascript/mastodon/features/circle_statuses/index.jsx
app/javascript/mastodon/features/compose/components/circle_select.jsx
app/javascript/mastodon/reducers/circles.js
app/javascript/mastodon/selectors/index.js

Fix: #154 サークル投稿履歴が遡れない問題

---

app/models/status.rb
app/services/fan_out_on_write_service.rb
spec/services/fan_out_on_write_service_spec.rb

Add: #136 自分が引用した投稿が編集されたときに通知

---

app/helpers/context_helper.rb
app/lib/activitypub/activity/create.rb
app/lib/activitypub/activity/like.rb
app/lib/activitypub/parser/custom_emoji_parser.rb
app/serializers/activitypub/emoji_serializer.rb
app/services/activitypub/process_status_update_service.rb

Add: カスタム絵文字のエイリアス名を連合

---

app/models/account.rb
app/validators/emoji_reaction_validator.rb
spec/models/account_spec.rb

Fix: 他のサーバー同士のスタンプで`emoji_reaction_policy`が適用される問題

---

app/views/admin/domain_blocks/_domain_block_list.html.haml
app/views/admin/domain_blocks/edit.html.haml
app/views/admin/domain_blocks/new.html.haml
config/locales/en.yml
config/locales/ja.yml

Add: #22 拡張ドメインブロックの設定画面に見出し

---

app/models/account.rb
spec/models/account_spec.rb

Fix: 他のサーバー同士のスタンプで`emoji_reaction_policy`が適用される問題 (LTS)

---

app/controllers/admin/custom_emojis_controller.rb
app/helpers/kmyblue_capabilities_helper.rb
app/lib/activitypub/activity/undo.rb
app/views/admin/custom_emojis/edit.html.haml
app/views/admin/custom_emojis/new.html.haml
db/post_migrate/20231022074913_add_statuses_quote_index.rb
db/schema.rb
lib/mastodon/version.rb
spec/lib/activitypub/activity/like_spec.rb
spec/lib/activitypub/activity/undo_spec.rb

Add: #173 カスタム絵文字新規作成・編集画面にカテゴリ選択欄

---

app/helpers/kmyblue_capabilities_helper.rb
app/lib/activitypub/activity/undo.rb
app/models/account.rb
app/models/concerns/account_other_settings.rb
db/post_migrate/20231022074913_add_statuses_quote_index.rb
db/schema.rb
lib/mastodon/version.rb
spec/lib/activitypub/activity/like_spec.rb
spec/lib/activitypub/activity/undo_spec.rb

Refactor: #160 アカウントのother_settings関連部分を別ファイルに切り出し

---

config/locales/simple_form.ja.yml

Fix: #193 リアクションデッキ表記を削除

---

app/javascript/mastodon/components/domain.tsx
app/javascript/mastodon/components/searchability_icon.tsx
app/javascript/mastodon/components/visibility_icon.tsx
app/javascript/mastodon/features/compose/components/privacy_dropdown.jsx
app/javascript/mastodon/features/compose/components/searchability_dropdown.jsx

Change: #197 非収載のアイコン変更

---

app/controllers/api/v1/statuses_controller.rb
app/javascript/mastodon/actions/statuses.js
spec/controllers/api/v1/statuses_controller_spec.rb

Add: #198 `context`のAPIに`with_references`パラメータを追加

---

app/javascript/mastodon/components/status_action_bar.jsx
app/javascript/mastodon/features/status/components/action_bar.jsx
app/javascript/mastodon/features/status/components/detailed_status.jsx
app/javascript/mastodon/initial_state.js
app/models/concerns/has_user_settings.rb
app/models/instance_info.rb
app/models/status.rb
app/models/user_settings.rb
app/presenters/status_relationships_presenter.rb
app/serializers/initial_state_serializer.rb
app/serializers/rest/status_serializer.rb
app/views/settings/preferences/appearance/show.html.haml
config/locales/simple_form.en.yml
config/locales/simple_form.ja.yml
spec/models/status_spec.rb

Add: #90 スタンプに対応していないと思われるサーバーの投稿からスタンプボタンを隠す設定

---

app/javascript/mastodon/actions/bookmarks.js
app/javascript/mastodon/actions/favourites.js
app/javascript/mastodon/actions/lists.js
app/javascript/mastodon/features/bookmarked_statuses/index.jsx
app/javascript/mastodon/features/favourited_statuses/index.jsx
app/javascript/mastodon/features/favourites/index.jsx
app/javascript/mastodon/features/list_adder/components/account.jsx
app/javascript/mastodon/features/list_adder/components/list.jsx
app/javascript/mastodon/features/list_adder/index.jsx
app/javascript/mastodon/features/list_editor/components/account.jsx
app/javascript/mastodon/features/list_editor/components/edit_list_form.jsx
app/javascript/mastodon/features/list_editor/components/search.jsx
app/javascript/mastodon/features/list_editor/index.jsx
app/javascript/mastodon/features/list_timeline/index.jsx
app/javascript/mastodon/features/lists/components/new_list_form.jsx
app/javascript/mastodon/features/lists/index.jsx
app/javascript/mastodon/reducers/list_adder.js
app/javascript/mastodon/reducers/list_editor.js
app/javascript/mastodon/reducers/lists.js

Add: #189 本家由来の独自機能作成時に参考にしたファイルにマーカー

---

app/javascript/mastodon/features/compose/components/compose_form.jsx
app/javascript/mastodon/reducers/compose.js

Fix: #221 投稿フォームの時限投稿メニューが動作しない問題

---

app/controllers/api/v1/statuses/emoji_reactions_controller.rb
app/lib/activitypub/activity/like.rb
app/lib/activitypub/activity/undo.rb
app/lib/status_reach_finder.rb
app/services/emoji_react_service.rb
app/services/un_emoji_react_service.rb
app/workers/activitypub/emoji_reaction_distribution_worker.rb
spec/services/emoji_react_service_spec.rb
spec/services/un_emoji_react_service_spec.rb

Change: #185 『スタンプをつけられた人』ではなく『スタンプをつけた人』のフォロワーにスタンプを転送

---

app/serializers/activitypub/emoji_reaction_serializer.rb

Change: スタンプの`id`をお気に入りと区別できるよう変更

---

app/javascript/mastodon/features/about/index.jsx
app/javascript/styles/mastodon/about.scss

Change: #186 概要画面のkmyblue capabilities表示改善

---

app/helpers/kmyblue_capabilities_helper.rb

Add: #207 リスト通知機能を`fedibird_capabilities`に追加

---

app/javascript/mastodon/features/about/index.jsx
app/javascript/mastodon/locales/en.json
app/javascript/mastodon/locales/ja.json

Add: #245 概要画面に全文検索の項目

---

app/services/fan_out_on_write_service.rb
spec/services/fan_out_on_write_service_spec.rb

Fix: #264 ハッシュタグをフォローしていても、非収載投稿がホームに流れない問題

---

install/9.0/setup-imagemagick-7.sh
install/9.0/setup1.sh
install/9.0/setup2.sh
install/9.0/setup3.sh
install/9.0/setup4.sh

Fix: セットアップスクリプトの`yarn install`でエラーが出る／`latest`を追加

---

app/views/admin/custom_emojis/edit.html.haml
app/views/admin/custom_emojis/new.html.haml

Fix: #301 カスタム絵文字編集時、カテゴリ選択の初期値の異常

---

app/lib/activitypub/activity/like.rb
spec/lib/activitypub/activity/like_spec.rb

Change: #326 ドメインブロックで「制限」を行っているサーバーからのスタンプは、ローカルフォロワーの投稿に対するもののみ受け入れる

---

CHANGELOG.md
app/chewy/accounts_index.rb
app/chewy/concerns/datetime_clamping_concern.rb
app/chewy/public_statuses_index.rb
app/chewy/statuses_index.rb
app/chewy/tags_index.rb
app/javascript/mastodon/components/dismissable_banner.tsx
app/javascript/mastodon/reducers/settings.js
app/javascript/styles/mastodon/components.scss
app/models/concerns/attachmentable.rb
docker-compose.yml

※本家の4.2.2より差分が少ないように見えるが、9.0の時点で本家追従している分はすでに入ってて取り込み不要なので少ないように見えるだけ

Release: 9.1

---

Gemfile.lock
lib/mastodon/version.rb

Release: 9.2

---

app/serializers/rest/status_serializer.rb
app/services/process_references_service.rb
spec/services/process_references_service_spec.rb

Fix: #94 `ProcessReferencesService`リファクタリング・編集時の参照引用変更バグ修正

---

app/models/concerns/account/other_settings.rb
app/models/concerns/user/has_settings.rb
app/models/user_settings.rb
app/views/settings/preferences/other/show.html.haml
config/locales/simple_form.en.yml
config/locales/simple_form.ja.yml
spec/models/account_spec.rb

Add: #30 ローカルユーザーからのスタンプに関するポリシー設定

---

.rubocop_todo.yml
db/migrate/20231212225737_improve_index_for_public_timeline_speed.rb
db/schema.rb

Fix: #355 LTLのインデックスが適切にはられていない問題 (LTS)

---

app/controllers/admin/special_instances_controller.rb
app/models/concerns/account/other_settings.rb
app/models/form/admin_settings.rb
app/views/admin/special_instances/show.html.haml
config/locales/en.yml
config/locales/ja.yml
config/navigation.rb
config/routes/admin.rb
config/settings.yml
spec/models/account_spec.rb

Add: #363 特定サーバーの投稿にスタンプを付けることを禁止する管理者設定

---

app/helpers/kmyblue_capabilities_helper.rb
app/javascript/mastodon/features/compose/components/searchability_dropdown.jsx
app/javascript/mastodon/reducers/compose.js
app/models/status.rb
app/services/post_status_service.rb
app/views/admin/settings/discovery/show.html.haml
config/locales/simple_form.en.yml
config/locales/simple_form.ja.yml

Change: #246 公開範囲「ローカル公開」無効と同時に、検索許可「ローカルとフォロワー」も無効にする

---

app/javascript/mastodon/features/compose/components/compose_form.jsx

Add: #281 限定投稿時の投稿ボタンに盾マーク

---

config/locales/simple_form.ja.yml

Fix: 日本語訳で未収載を非収載に変更

---

app/javascript/mastodon/components/status_action_bar.jsx
app/javascript/mastodon/features/status/components/action_bar.jsx

Change: #272 スタンプのボタンの順番を入れ替え

---

app/javascript/mastodon/actions/compose.js

Fix: #371 サークルを選んだ状態でサークル以外の公開範囲で投稿した場合、投稿履歴に投稿が追加される

---

app/helpers/kmyblue_capabilities_helper.rb

Change: #366 NodeInfoの`features`の数を絞る

---

app/helpers/kmyblue_capabilities_helper.rb
app/javascript/mastodon/features/about/index.jsx
app/serializers/rest/instance_serializer.rb
app/serializers/rest/v1/instance_serializer.rb

Change: #322 `fedibird_capabilities`から`profile_search`を削除

---

app/javascript/mastodon/api_types/accounts.ts
app/javascript/mastodon/models/account.ts
app/models/concerns/account/other_settings.rb
app/models/concerns/user/has_settings.rb
app/models/user_settings.rb
app/views/accounts/show.html.haml
app/views/settings/privacy/show.html.haml
app/views/statuses/show.html.haml
config/locales/simple_form.en.yml
config/locales/simple_form.ja.yml

Remove: #358 「自分のコンテンツのAI学習利用に対して不快感を表明する」設定

---

app/lib/activitypub/activity/like.rb
app/lib/activitypub/activity/undo.rb
app/models/form/admin_settings.rb
app/services/emoji_react_service.rb
app/services/un_emoji_react_service.rb
app/views/admin/settings/discovery/show.html.haml
config/locales/simple_form.en.yml
config/locales/simple_form.ja.yml
config/settings.yml

Add: #384 スタンプのストリーミングを全停止する管理者設定

---

app/serializers/rest/filter_serializer.rb

本家で問題が指摘されています
https://github.com/mastodon/mastodon/issues/27622
根本対応ではありませんが本家が対応するまでこれで様子見ます

Fix: フィルター使用中にエラーが出る場合がある問題の暫定対応

---

app/serializers/rest/filter_serializer.rb

Reverts kmycode/mastodon#395
Mastodon本家がこの問題に対応したためRevertします（やってることはうちと大体一緒のようです）
https://github.com/mastodon/mastodon/pull/28521
**NOTE** １月３日以降の数日間で新しく`kb_development`の最新コミットでkmyblueフォークを建ててしまう人がいるかもしれないので、このPRは次回の本家取り込み時にマージします

Revert "Fix: フィルター使用中にエラーが出る場合がある問題の暫定対応"

---

app/javascript/mastodon/components/visibility_icon.tsx
app/javascript/mastodon/features/status/index.jsx
app/javascript/mastodon/locales/en.json

Fix: 参照付き投稿の詳細画面のキーボード操作不具合・規定のスクロール量不具合

---

app/javascript/mastodon/actions/notifications.js
app/javascript/mastodon/components/status.jsx
app/javascript/mastodon/reducers/filters.js
app/javascript/mastodon/selectors/index.js
app/serializers/rest/filter_serializer.rb
streaming/index.js

Fix: #404 フィルターで`half_warn`を設定してると、クライアントアプリでタイムラインが読み込まれない

---

app/javascript/mastodon/components/status_emoji_reactions_bar.jsx
app/javascript/mastodon/initial_state.js
app/models/concerns/user/has_settings.rb
app/models/user_settings.rb
app/serializers/initial_state_serializer.rb
app/views/settings/preferences/appearance/show.html.haml
config/locales/simple_form.en.yml
config/locales/simple_form.ja.yml

Add: #396 スタンプの数字を隠して表示する機能

---

app/lib/activitypub/activity/like.rb
app/lib/activitypub/activity/undo.rb
app/models/form/admin_settings.rb
app/services/emoji_react_service.rb
app/services/un_emoji_react_service.rb
app/views/admin/settings/discovery/show.html.haml
config/locales/simple_form.en.yml
config/locales/simple_form.ja.yml
config/settings.yml

Change: #398 管理者設定：スタンプのストリーミングを有効にする設定→ローカルユーザーの絡むスタンプのストリーミングを有効にする

---

app/javascript/mastodon/components/compacted_status.jsx

Fix: #415 引用付き投稿を引用したものにおいて、キーボードによる投稿選択がエラーでできない

---

app/javascript/mastodon/components/status_action_bar.jsx
app/javascript/mastodon/features/status/components/action_bar.jsx

Change: 投稿下のアクションバーにおけるスタンプボタンの順番

---

app/serializers/node_info/serializer.rb

Change: #369 ソフトウェア名を`mastodon`から`kmyblue`に変更する

---

app/controllers/api/v1/admin/domain_blocks_controller.rb
app/models/domain_block.rb
db/migrate/20240109035435_remove_hidden_anonymous_from_domain_blocks.rb
db/schema.rb
spec/requests/api/v1/instances/domain_blocks_spec.rb

Add: #437 ドメインブロックで「未ログインユーザーに非公開」の設定を「非公開」にコピーするマイグレーションコード

---

lib/mastodon/version.rb

Release: 10.0

---

app/models/concerns/account/other_settings.rb
app/models/concerns/user/has_settings.rb
app/models/user_settings.rb
app/services/fetch_link_card_service.rb
app/views/settings/privacy_extra/show.html.haml
config/locales/simple_form.en.yml
config/locales/simple_form.ja.yml
spec/models/account_spec.rb
spec/services/fetch_link_card_service_spec.rb

Remove: #454 リンクプレビューを生成する設定の削除、無効化

---

app/models/domain_block.rb
config/locales/en.yml
config/locales/ja.yml
db/post_migrate/20240117022353_remove_legacy_domain_block_columns.rb
db/schema.rb
lib/tasks/dangerous.rake

Remove: #372 ドメインブロックにおいて、DBの不要なカラムを削除

---

app/lib/search_query_transformer.rb
app/models/concerns/user/has_settings.rb
app/models/user_settings.rb
app/views/settings/preferences/reaching/show.html.haml
config/locales/simple_form.en.yml
config/locales/simple_form.ja.yml
spec/search/services/statuses_search_service_spec.rb

Add: #452 全文検索で、ダブルクオートがない場合でも単語検索を標準とするオプション

---

spec/policies/status_policy_spec.rb

Test: #76 `StatusPolicy`における拡張ドメインブロックのテスト

---

app/services/concerns/account_scope.rb

Fix: #303 限定投稿のスタンプがストリーミングできていない

---

Dockerfile
lib/mastodon/version.rb

Release: 10.2

---

app/services/remove_status_service.rb

Fix: #494 投稿削除がストリーミングされない問題

---

app/controllers/admin/export_domain_blocks_controller.rb
app/models/admin/import.rb
spec/controllers/admin/export_domain_blocks_controller_spec.rb
spec/fixtures/files/domain_blocks.csv
spec/models/form/import_spec.rb

Add: #374 拡張ドメインブロックのインポート・エクスポートについてkmyblue独自の項目のサポート

---

app/javascript/mastodon/features/getting_started/index.jsx
app/javascript/mastodon/locales/en.json
app/javascript/mastodon/locales/ja.json

Fix: #467 上級者向けUIのスタートメニューにDTLが表示されない

---

app/javascript/mastodon/actions/notifications.js
app/javascript/mastodon/features/notifications/components/column_settings.jsx
app/javascript/mastodon/features/notifications/components/filter_bar.jsx
spec/controllers/auth/registrations_controller_spec.rb

Fix: #517 「絵文字リアクション機能を使用する」設定を無効にしている時、絵文字リアクションの通知も表示されないようにする

---

app/javascript/styles/mastodon/components.scss
app/javascript/styles/mastodon/tables.scss
app/javascript/styles/mastodon/widgets.scss

Change: #475 絵文字リアクションの絵文字サイズをもう少し大きく

---

app/lib/activitypub/activity/like.rb
app/models/emoji_reaction.rb
app/serializers/rest/instance_serializer.rb
app/serializers/rest/v1/instance_serializer.rb

Add: #446 スタンプ上限の設定を、ローカルユーザー向けと外部サーバーユーザー向けのものに分ける

---

app/lib/admin/system_check/sidekiq_process_check.rb
app/workers/delivery_emoji_reaction_worker.rb
config/sidekiq.yml
spec/lib/admin/system_check/sidekiq_process_check_spec.rb

Change: #420 絵文字リアクションストリーミングWorkerのキューの種類を新規作成

---

app/javascript/mastodon/features/explore/results.jsx
app/javascript/mastodon/features/explore/statuses.jsx
app/javascript/mastodon/utils/filters.ts
app/models/custom_filter.rb
config/locales/en.yml
config/locales/ja.yml

Add: #400 検索結果・トレンドのフィルター

---

app/helpers/kmyblue_capabilities_helper.rb
app/javascript/mastodon/features/about/index.jsx
app/javascript/mastodon/features/compose/components/privacy_dropdown.jsx
app/javascript/mastodon/initial_state.js
app/javascript/mastodon/locales/ja.json
app/javascript/mastodon/reducers/compose.js
app/models/form/admin_settings.rb
app/models/status.rb
app/serializers/initial_state_serializer.rb
app/services/post_status_service.rb
app/views/admin/settings/discovery/show.html.haml
config/locales/simple_form.en.yml
config/locales/simple_form.ja.yml
config/settings.yml

Add: #559 公開投稿を禁止する管理者設定

---

app/services/reblog_service.rb
spec/services/reblog_service_spec.rb

Change: #576 公開範囲「公開」を禁止する設定について、ブーストにも適用されるように

---

app/models/form/admin_settings.rb
app/services/activitypub/process_account_service.rb
app/views/admin/ng_words/show.html.haml
config/locales/en.yml
config/locales/ja.yml
spec/services/activitypub/process_account_service_spec.rb

Add: #573 新規のアカウント認識を全て停止するオプション

---

app/controllers/admin/accounts_controller.rb
app/models/account.rb
app/views/admin/accounts/_buttons.html.haml
config/locales/en.yml
config/locales/ja.yml
config/routes/admin.rb

Fix: #588 リモート保留中ユーザーに関して、サスペンドから戻す操作を削除

---

app/helpers/follow_helper.rb
app/lib/activitypub/activity/follow.rb
app/models/account.rb
app/models/concerns/account/interactions.rb
app/models/follow_request.rb
app/models/pending_follow_request.rb
app/services/activitypub/process_collection_service.rb
app/services/delete_account_service.rb
app/services/enable_follow_requests_service.rb
app/workers/enable_follow_requests_worker.rb
db/migrate/20240217230006_create_pending_follow_requests.rb
db/schema.rb
lib/tasks/dangerous.rake
spec/fabricators/pending_follow_request_fabricator.rb
spec/lib/activitypub/activity/follow_spec.rb
spec/services/enable_follow_requests_service_spec.rb

Add: #586 保留中のリモートアカウントからのフォローが飛んできた場合に記録する

---

app/services/activitypub/process_status_update_service.rb
config/locales/en.yml
config/locales/ja.yml
spec/services/activitypub/process_status_update_service_spec.rb

Closes #556 
結論から言うと、新規投稿処理ではすでに考慮されていました
投稿編集時の処理がなかったので足しました

Change: #556 ドメインブロック「フォローされていない相手からのリプライを拒否」に、参照を含める

---

app/controllers/admin/custom_emojis_controller.rb

Fix: #542 カスタム絵文字を編集した回数だけ「追加しました」ログが記録される

---

app/javascript/mastodon/features/account/components/header.jsx
app/javascript/mastodon/features/followers/index.jsx
app/javascript/mastodon/features/following/index.jsx
app/javascript/mastodon/initial_state.js
app/models/concerns/user/has_settings.rb
app/models/user_settings.rb
app/serializers/initial_state_serializer.rb
app/views/settings/preferences/appearance/show.html.haml
config/locales/simple_form.en.yml
config/locales/simple_form.ja.yml

Add: #36 アカウント詳細画面の「フォローされています」を隠すオプション

---

app/views/settings/privacy_extra/show.html.haml
config/locales/en.yml
config/locales/ja.yml

Add: #626 購読許可を将来的に削除する注意書き

---

lib/mastodon/version.rb

Release: 11.3

---

.gitignore
app/chewy/accounts_index.rb
app/chewy/public_statuses_index.rb
app/chewy/statuses_index.rb
app/chewy/tags_index.rb
app/lib/chewy_config.rb
config/elasticsearch.default-ja-sudachi.yml
config/elasticsearch.default.yml
config/initializers/chewy.rb

Change: #532 ElasticSearch設定の外出し

---

.haml-lint_todo.yml
app/controllers/admin/sensitive_words_controller.rb
app/javascript/packs/admin.tsx
app/javascript/styles/mastodon/forms.scss
app/models/admin/sensitive_word.rb
app/models/form/admin_settings.rb
app/models/sensitive_word.rb
app/views/admin/sensitive_words/_sensitive_word.html.haml
app/views/admin/sensitive_words/show.html.haml
config/locales/en.yml
config/locales/ja.yml
db/migrate/20240312230204_create_sensitive_words.rb
db/schema.rb
spec/fabricators/sensitive_word_fabricator.rb
spec/lib/activitypub/activity/create_spec.rb
spec/models/admin/sensitive_word_spec.rb
spec/services/activitypub/process_status_update_service_spec.rb

Change: #648 センシティブワードの入力フォーム

---

app/javascript/mastodon/actions/compose.js
app/javascript/mastodon/features/compose/components/compose_form.jsx
app/javascript/mastodon/features/compose/components/featured_tags_dropdown.jsx
app/javascript/mastodon/features/compose/containers/compose_form_container.js
app/javascript/mastodon/features/compose/containers/featured_tags_dropdown_container.js
app/javascript/mastodon/initial_state.js
app/javascript/mastodon/locales/en.json
app/javascript/mastodon/locales/ja.json
app/javascript/mastodon/reducers/compose.js
app/serializers/initial_state_serializer.rb

Add: #91 アカウントのおすすめタグを投稿フォームからクリックで挿入可能にする

---

app/javascript/styles/mastodon/forms.scss
app/views/settings/profiles/show.html.haml
config/locales/simple_form.en.yml
config/locales/simple_form.ja.yml

Change: フィールド入力フォームのデザイン改善

---

db/post_migrate/20240326231854_improve_preview_cards_vacuum.rb
db/schema.rb
lib/tasks/dangerous.rake

Add: #641 `preview_cards`、`media_attachments`にインデックスを追加

---

app/models/trends/tags.rb
spec/models/trends/tags_spec.rb

問い合わせ者に対しては負荷の関係で難しいと回答してましたが、改めて調査したところできるようだったので

Fix: ドメインブロックのトレンド掲載を拒否に、ハッシュタグが含まれない問題

---

app/javascript/mastodon/features/antenna_setting/index.jsx
app/javascript/mastodon/features/antenna_timeline/index.jsx
app/javascript/mastodon/features/circle_statuses/index.jsx

Fix: #657 アンテナ、サークルの詳細設定ペインのデザイン崩れ

---

app/javascript/mastodon/actions/notifications.js
app/javascript/mastodon/actions/streaming.js
app/javascript/mastodon/reducers/statuses.js

Fix: #660 絵文字リアクションのストリーミングを受信した時点で投稿のカウントが更新されない

---

AUTHORS_KB.md
app/controllers/admin/statuses_controller.rb
app/javascript/mastodon/actions/compose.js
app/javascript/mastodon/actions/importer/index.js
app/javascript/mastodon/reducers/compose.js
app/javascript/styles/full-dark/diff.scss
app/javascript/styles/mastodon/components.scss
app/models/admin/status_batch_action.rb
app/models/concerns/account/interactions.rb
app/models/instance_info.rb
app/models/trends/tags.rb
app/services/approve_appeal_service.rb
app/services/post_status_service.rb
app/services/update_status_service.rb
app/workers/activitypub/fetch_instance_info_worker.rb
lib/mastodon/version.rb
spec/models/trends/tags_spec.rb
spec/services/post_status_service_spec.rb
spec/services/update_status_service_spec.rb

Release: 11.4

---

app/javascript/mastodon/api_types/accounts.ts
app/javascript/mastodon/components/status.jsx
app/javascript/mastodon/components/status_action_bar.jsx
app/javascript/mastodon/features/status/components/action_bar.jsx
app/javascript/mastodon/features/status/components/detailed_status.jsx
app/javascript/mastodon/initial_state.js
app/javascript/mastodon/models/account.ts
app/lib/entity_cache.rb
app/models/concerns/user/has_settings.rb
app/models/instance_info.rb
app/models/status.rb
app/models/user_settings.rb
app/presenters/status_relationships_presenter.rb
app/serializers/initial_state_serializer.rb
app/serializers/rest/account_serializer.rb
app/views/settings/preferences/appearance/show.html.haml
config/locales/en.yml
config/locales/ja.yml
config/locales/simple_form.en.yml
config/locales/simple_form.ja.yml
spec/models/instance_info_spec.rb
spec/models/status_spec.rb

Add: #699 引用・参照対応サーバーをAPIで取得

---

app/serializers/rest/custom_emoji_serializer.rb

Add: #510 カスタム絵文字取得APIにライセンス情報を付加

---

app/lib/activitypub/activity/create.rb
app/serializers/activitypub/note_serializer.rb
spec/lib/activitypub/activity/create_spec.rb
spec/serializers/activitypub/note_serializer_spec.rb

Fedibirdが対応してたので
すでにThreads、Pleromaなどが対応済

Add: fep-e232引用仕様

---

install/12.0/setup-imagemagick-7.sh
install/12.0/setup1.sh
install/12.0/setup2.sh

Gitリポジトリのチェックアウトがrootからできるかが一番のネック
それさえできればセットアップスクリプトの数は半分になるんだけども

Change: 自動セットアップスクリプトを改善
