kmycode/mastodon

app/controllers/api/v1/circles/statuses_controller.rb
app/javascript/mastodon/actions/circles.js
app/javascript/mastodon/actions/compose.js
app/javascript/mastodon/features/circle_statuses/index.jsx
app/javascript/mastodon/features/circles/index.jsx
app/javascript/mastodon/features/ui/components/columns_area.jsx
app/javascript/mastodon/features/ui/index.jsx
app/javascript/mastodon/features/ui/util/async-components.js
app/javascript/mastodon/reducers/circles.js
app/javascript/mastodon/selectors/index.js
app/models/circle.rb
app/models/circle_status.rb
app/models/status.rb
app/services/process_mentions_service.rb
config/routes.rb
config/routes/api.rb
db/migrate/20230923103430_create_circle_statuses.rb
db/schema.rb
spec/services/process_mentions_service_spec.rb

Add circle posts history support

---

app/controllers/api/v1/statuses/mentioned_accounts_controller.rb
app/javascript/mastodon/actions/interactions.js
app/javascript/mastodon/components/status_action_bar.jsx
app/javascript/mastodon/features/mentioned_users/index.jsx
app/javascript/mastodon/features/status/components/action_bar.jsx
app/javascript/mastodon/features/ui/index.jsx
app/javascript/mastodon/features/ui/util/async-components.js
app/javascript/mastodon/reducers/circles.js
app/javascript/mastodon/reducers/user_lists.js
app/models/mention.rb
app/policies/status_policy.rb
config/routes/api.rb
spec/controllers/api/v1/statuses/mentioned_accounts_controller_spec.rb

Add mentioned users by status view

---

app/javascript/mastodon/features/compose/components/searchability_dropdown.jsx
app/javascript/mastodon/features/status/components/detailed_status.jsx
app/javascript/mastodon/locales/en.json
app/javascript/mastodon/locales/ja.json
app/lib/account_statuses_filter.rb
app/lib/importer/statuses_index_importer.rb
app/lib/search_query_transformer.rb
app/models/concerns/status_search_concern.rb
app/models/status.rb
app/models/trends/statuses.rb
app/serializers/rest/status_serializer.rb
app/services/delivery_antenna_service.rb
app/services/fan_out_on_write_service.rb
app/services/post_status_service.rb
app/views/settings/preferences/reaching/show.html.haml
config/locales/en.yml
config/locales/ja.yml
spec/lib/status_reach_finder_spec.rb
spec/models/status_spec.rb
spec/models/tag_feed_spec.rb
spec/search/services/statuses_search_service_spec.rb
spec/serializers/activitypub/note_serializer_spec.rb
spec/services/fan_out_on_write_service_spec.rb
spec/services/post_status_service_spec.rb

Add: 検索許可「ローカルとフォロワー」

---

app/lib/activitypub/activity/like.rb
app/lib/activitypub/parser/custom_emoji_parser.rb
app/lib/activitypub/tag_manager.rb
app/serializers/activitypub/emoji_serializer.rb
spec/lib/activitypub/activity/like_spec.rb

Closes #64 
※`ActivityPub::EmojiSerializer`に`domain`プロパティを追加。現行ではIDをURLとみなしてそこから抽出しているが、vivaldi.netのようにWebとドメインが異なるケースを考慮

他サーバーからカスタム絵文字によるスタンプを受け取った時に、ライセンス情報を保存する＋ついでにテスト

---

app/lib/activitypub/activity/create.rb
app/lib/activitypub/parser/status_parser.rb
spec/lib/activitypub/activity/create_spec.rb

Change: #75 フレンドでないサーバーからのローカル公開を未収載に変換

---

app/controllers/settings/privacy_controller.rb
app/controllers/settings/privacy_extra_controller.rb
app/helpers/kmyblue_capabilities_helper.rb
app/lib/activitypub/activity/follow.rb
app/lib/feed_manager.rb
app/lib/status_reach_finder.rb
app/models/emoji_reaction.rb
app/models/friend_domain.rb
app/serializers/nodeinfo/serializer.rb
app/services/emoji_react_service.rb
app/views/settings/privacy/show.html.haml
app/views/settings/privacy_extra/show.html.haml
lib/mastodon/version.rb
spec/lib/activitypub/activity/follow_spec.rb
spec/lib/feed_manager_spec.rb
spec/lib/status_reach_finder_spec.rb
spec/models/friend_domain_spec.rb
spec/serializers/nodeinfo/serializer_spec.rb
spec/serializers/rest/instance_serializer_spec.rb
spec/services/emoji_react_service_spec.rb

Bump version to 7.1

---

app/controllers/settings/privacy_controller.rb
app/controllers/settings/privacy_extra_controller.rb
app/lib/feed_manager.rb
app/models/emoji_reaction.rb
app/services/emoji_react_service.rb
app/views/settings/privacy/show.html.haml
app/views/settings/privacy_extra/show.html.haml
lib/mastodon/version.rb
spec/fabricators/emoji_reaction_fabricator.rb
spec/lib/feed_manager_spec.rb
spec/services/emoji_react_service_spec.rb

Bump version to 5.5 LTS

---

app/models/status.rb
spec/services/post_status_service_spec.rb

Change: #68 限定投稿の検索許可を反応者に設定可能に

---

app/javascript/mastodon/features/bookmark_category_statuses/index.jsx
app/javascript/mastodon/features/bookmarked_statuses/index.jsx
app/javascript/mastodon/features/circle_statuses/index.jsx
app/javascript/mastodon/features/emoji_reacted_statuses/index.jsx
app/javascript/mastodon/features/favourited_statuses/index.jsx

Fix: ブックマーク・ブックマーク分類・サークル・お気に入り・スタンプの投稿一覧で、ヘッダを押してもスクロールできない問題（本家由来）

---

app/controllers/admin/custom_emojis_controller.rb
app/models/custom_emoji.rb
app/models/form/custom_emoji_batch.rb
app/views/admin/custom_emojis/_custom_emoji.html.haml
app/views/admin/custom_emojis/edit.html.haml
app/views/admin/custom_emojis/index.html.haml
app/views/admin/custom_emojis/new.html.haml
config/locales/en.yml
config/locales/ja.yml
config/routes/admin.rb

Add: カスタム絵文字の専用編集画面／Fix: リモートの絵文字をローカルにコピー時、ライセンス情報が消失する問題

---

app/models/form/admin_settings.rb
app/services/post_status_service.rb
app/views/admin/ng_words/show.html.haml
config/locales/en.yml
config/locales/ja.yml
config/settings.yml
spec/services/post_status_service_spec.rb

Change: #150 ローカルユーザーの投稿にもメンションのNGワードを適用

---

app/services/concerns/payloadable.rb
spec/services/backup_service_spec.rb

`BackupService`がエラーで落ちる問題に対処
Bearcap処理まわりをいじったので、以下の動作確認が必要

Fix: ブーストが１つでもあると投稿のエクスポート時にエラーが出る問題

---

app/services/activitypub/process_status_update_service.rb
app/services/post_status_service.rb
app/services/update_status_service.rb
spec/services/activitypub/process_status_update_service_spec.rb
spec/services/post_status_service_spec.rb
spec/services/update_status_service_spec.rb

Closes #162
Closes #44
テストは問題なく通っているが、念のためサーバーテストもしたい

Fix: #162 編集／他のサーバーからの編集で、フォローしていない相手からのメンションに関するNGワードに対応

---

app/lib/activitypub/activity/like.rb
app/lib/activitypub/activity/undo.rb
app/models/account.rb
app/models/concerns/account_interactions.rb
app/serializers/activitypub/emoji_serializer.rb
lib/mastodon/version.rb
spec/lib/activitypub/activity/like_spec.rb
spec/lib/activitypub/activity/undo_spec.rb
spec/models/account_spec.rb

Bump version to 5.7 LTS

---

app/helpers/kmyblue_capabilities_helper.rb
app/lib/activitypub/activity/like.rb
app/lib/activitypub/activity/undo.rb
app/serializers/activitypub/emoji_serializer.rb
db/post_migrate/20231022074913_add_statuses_quote_index.rb
db/schema.rb
lib/mastodon/version.rb
spec/lib/activitypub/activity/like_spec.rb
spec/lib/activitypub/activity/undo_spec.rb

Bump version to 8.0

---

app/models/instance_info.rb

Fix: #217 スタンプ利用可能なソフトウェア名から`kmyblue`を削除

---

app/models/instance_info.rb

Fix: #220 インスタンス情報更新時に、スタンプ利用可否のキャッシュをクリアする処理

---

app/javascript/mastodon/features/status/index.jsx

Fix: #236 ログインしていない状態で投稿詳細画面でスタンプを押そうとすると画面が操作不能になる

---

app/javascript/mastodon/components/dropdown_menu.jsx

Fix: #205 投稿の編集履歴一覧ポップアップが表示できない

---

app/javascript/mastodon/components/status.jsx
app/javascript/mastodon/components/status_action_bar.jsx
app/javascript/mastodon/features/compose/containers/emoji_picker_dropdown_container.js
app/javascript/mastodon/features/status/components/action_bar.jsx
app/javascript/mastodon/features/status/components/detailed_status.jsx
app/javascript/mastodon/features/ui/components/navigation_panel.jsx
app/javascript/mastodon/initial_state.js
app/javascript/mastodon/selectors/index.js
app/models/concerns/has_user_settings.rb
app/models/user_settings.rb
app/serializers/initial_state_serializer.rb
app/views/settings/preferences/appearance/show.html.haml
config/locales/simple_form.en.yml
config/locales/simple_form.ja.yml

Add: #213 右サイドメニューからお気に入りを削除するオプション

---

app/models/emoji_reaction.rb

Fix: 環境変数でスタンプの最大数を指定した場合、スタンプつけるときにエラーになる問題 (LTS)

---

app/models/emoji_reaction.rb

Closes #288 
PRには含まれないが以下のコードでもテスト済
```ruby
EMOJI_REACTION_PER_ACCOUNT_LIMIT = ENV.fetch('EMOJI_REACTION_PER_ACCOUNT_LIMIT', '3').to_i
```

Fix: 環境変数でスタンプの最大数を指定した場合、スタンプつけるときにエラーになる問題

---

app/lib/activitypub/tag_manager.rb
app/lib/status_reach_finder.rb
app/workers/activitypub/distribution_worker.rb
spec/workers/activitypub/distribution_worker_spec.rb

Change: サークルの送り先アカウント指定方法を`account_username`（Fedibirdと同様）に変更

---

app/lib/activitypub/tag_manager.rb
app/lib/status_reach_finder.rb
app/workers/activitypub/distribution_worker.rb
spec/workers/activitypub/distribution_worker_spec.rb

* Change: サークルの送り先アカウント指定方法を`account_username`（Fedibirdと同様）に変更
* Test: テストを追加
* Maybe Fix: Fedibirdで自分限定と認識される問題

Change: サークルの送り先アカウント指定方法を`account_username`（Fedibirdと同様）に変更 (#283) (LTS)

---

app/lib/feed_manager.rb
app/lib/status_cache_hydrator.rb
app/models/concerns/account_interactions.rb
app/models/custom_filter.rb
app/presenters/status_relationships_presenter.rb
app/services/delivery_antenna_service.rb
app/workers/feed_insert_worker.rb

Fix #304 
#304 の解消対応となります。
対応としては [RuboCopのガイドにある例](https://docs.rubocop.org/rubocop/cops_style.html#styleoptionalbooleanparameter) を元にオプション引数でbooleanを指定していた部分をキーワード引数に置き換えています。

Fix rubocop:disable Style/OptionalBooleanParameter

---

.github/workflows/elasticsearch-settings/elasticsearch.yml
.github/workflows/test-ruby.yml

Fix #298
#298 の警告抑制対応になります。
対応としては `etc//elasticsearch/elasticsearch.yml` をCI上で追加するようにして、セキュリティ周りの警告を抑制するようにしています。

Supress Elasticsearch warnings for GitHub Actions

---

app/javascript/mastodon/components/status.jsx
app/javascript/mastodon/features/status/components/detailed_status.jsx

Closes #280
詳細画面で表示されないのが問題ではなく、タイムラインで表示されるのが問題でした
このバグは、『スタンプに対応していないと思われるサーバーの投稿からスタンプボタンを隠す』という設定を有効にしている時に発生します。
スタンプが有効でないサーバーの投稿詳細画面ではスタンプは非表示になっているのに、タイムラインでは表示される状態だったものです。

Fix: #280 タイムラインでスタンプが意図せず表示されることがある問題

---

app/javascript/mastodon/components/status_action_bar.jsx
app/javascript/mastodon/features/status/components/action_bar.jsx

Fix: #397 管理者やユーザーがスタンプ機能を無効にしているときに、投稿のボタン群を以前通り均等幅で詰めるようにする

---

app/serializers/rest/filter_serializer.rb
streaming/index.js

Fix: #416 フィルターでhalf_warnを指定した時の代替値指定ミス

---

app/workers/feed_insert_worker.rb

Fix: #421 リスト新着投稿通知処理を、リードレプリカの中から外す

---

app/javascript/styles/full-dark/diff.scss

Fix: #419 フルダークテーマでのplaceholderテキストを薄くする

---

app/controllers/admin/domain_blocks_controller.rb
app/controllers/api/v1/instances/domain_blocks_controller.rb
app/models/domain_block.rb
app/views/admin/domain_blocks/edit.html.haml
app/views/admin/domain_blocks/new.html.haml
config/locales/ja.yml
spec/requests/api/v1/instances/domain_blocks_spec.rb

Remove: #429 ドメインブロックの「未ログインユーザーに非公開にする」オプション

---

app/models/custom_filter.rb
app/models/status.rb

参照先投稿の中身を見るフィルターが原因
引用ではない参照の中身を見ないように修正するのは簡単だけれど、今回はできるだけ仕様を変えないようにしました
今後の調査次第では、後日、負荷軽減を目的として「引用ではない参照先投稿も確認する」オプション（デフォルトでOFF）を追加する可能性はあります

Fix: タイムライン読み込み時のN+1問題

---

app/javascript/mastodon/api_types/accounts.ts
app/javascript/mastodon/components/status.jsx
app/javascript/mastodon/components/status_action_bar.jsx
app/javascript/mastodon/features/status/components/action_bar.jsx
app/javascript/mastodon/features/status/components/detailed_status.jsx
app/javascript/mastodon/models/account.ts
app/serializers/rest/account_serializer.rb
app/serializers/rest/status_serializer.rb

Change: #428 `emoji_reaction_available_server`プロパティを`Status`から`Account`オブジェクトに移動する

---

app/helpers/jsonld_helper.rb
app/javascript/mastodon/features/emoji/emoji_utils.js
app/lib/activitypub/parser/custom_emoji_parser.rb
app/models/custom_emoji.rb
app/serializers/rest/custom_emoji_serializer.rb
spec/models/custom_emoji_spec.rb
spec/models/form/custom_emoji_batch_spec.rb
spec/serializers/rest/custom_emoji_serializer_spec.rb

Fix: #442 カスタム絵文字のaliasesにnullが入る場合がある

---

.github/workflows/test-ruby.yml
lib/tasks/dangerous.rake

#469 の修正
一度本家に戻してから再びkmyblueにしたときの動作テスト
- `main`ブランチを参照しない
- 以下の場合にテストで落ちる
- `dangerous.rake`の書き方に問題がある場合、`dangerous:back_upstream`で落ちる
- `dangerous.rake`で消し忘れたテーブル・カラムがある場合、`db:migrate`で落ちる。マイグレーション履歴の場合、`db:migrate`または`rspec`で落ちる
- `dangerous.rake`で消しすぎてしまったテーブル・カラムがある場合、`rspec`で落ちる。マイグレーション履歴の場合、`db:migrate`または`rspec`で落ちる
ただし「本家のマイグレーションをkmyblueのものだと勘違いしてまるごと消してしまった場合」のカバーの一部は、このテストではできません。それこそ本家に戻る時に`db:migrate`を念入りにやってもらうしか無いと思います
他にも、kmyblue用のデータを本家で読み取れる形式へ戻し忘れた場合など、このテストも他のテストと同様、完璧に信頼できるとは限りませんので信じすぎには注意です

Test: 本家に戻ってから再びkmyblueを導入したときのテスト

---

app/controllers/statuses_controller.rb
app/lib/activitypub/tag_manager.rb
app/lib/status_reach_finder.rb
app/models/concerns/status/domain_block_concern.rb
app/models/concerns/user/has_settings.rb
app/models/status.rb
app/models/user_settings.rb
app/policies/status_policy.rb
config/locales/simple_form.en.yml
config/locales/simple_form.ja.yml
spec/lib/activitypub/tag_manager_spec.rb
spec/serializers/activitypub/note_for_misskey_serializer_spec.rb

テストサーバーで確認
- 「ローカル公開」検索許可「誰でも以外」
- 「ローカル公開」検索許可「誰でも」
- 「非収載」検索許可「誰でも以外」
- 「非収載」検索許可「誰でも」

Remove: 現在使われていないドメインブロック無視設定のデッドコード

---

app/lib/account_statuses_filter.rb
spec/lib/account_statuses_filter_spec.rb

Clsoes #373 
ドメインブロック対象に投稿を配送しないオプションを有効にしていても、対象がoutboxへフェッチした場合は対象投稿を返してしまう
これはセキュリティインシデントにすべきか悩んだが、outboxには認証なしでアクセスできるという迂回手段がもともと存在するため今回は扱わないこととした

Fix: ドメインブロックがOutboxにおいて動作しない問題

---

app/lib/status_reach_finder.rb
app/models/concerns/status/domain_block_concern.rb
app/services/post_status_service.rb
app/services/update_status_service.rb
app/workers/activitypub/status_update_distribution_worker.rb
spec/lib/activitypub/activity/update_spec.rb
spec/lib/status_reach_finder_spec.rb
spec/services/update_status_service_spec.rb

Change: #375 投稿を編集して拡張ドメインブロックの条件にひっかかる状態になった場合、対象サーバーには投稿削除のActivityを送信する

---

app/models/concerns/user/has_settings.rb
app/models/user_settings.rb
app/services/process_mentions_service.rb
app/views/settings/privacy_extra/show.html.haml
config/locales/simple_form.en.yml
config/locales/simple_form.ja.yml
spec/services/post_status_service_spec.rb

ちょっと我ながらこのオプションを作るのは気持ち悪いのですけども、ioがきちんと対応するまでつけます
現在、misskey.ioにおける限定投稿受信に問題点は３つあります。
https://kmy.blue/@software/111764768883753787
https://kmy.blue/@software/111810490533506890
ただ１つ目の問題に比べたら２／３つ目は些少なものです。１つ目の問題点は、限定投稿をするたびに相手に通知がいくことです。
サークル投稿であればmisskey.ioのユーザーをサークルに登録しないことで回避可能ですが、相互限定投稿はどうにもなりませんのでこれを避けるためのオプションが必要です。

Add: Misskeyに相互限定投稿を配送しないオプション

---

app/lib/activitypub/activity/like.rb
app/services/emoji_react_service.rb
spec/lib/activitypub/activity/like_spec.rb
spec/services/emoji_react_service_spec.rb

Change: #457 サイレンスされているユーザーに、フォロー相手以外への絵文字リアクションを禁止

---

config/locales/en.yml
config/locales/ja.yml

Fix: #502 ユーザー設定のログインユーザーのみ(ja.statuses.visibilities.login)の翻訳がない

---

app/javascript/mastodon/features/firehose/index.jsx
app/models/public_feed.rb
spec/models/public_feed_spec.rb
spec/requests/api/v1/timelines/public_spec.rb

リアルタイムフィードの「リモートのみ」タブを削除し、リモート＆ローカル全部あわせたタイムラインしか表示できないように
ローカルのことを意識してしまうため必要
ただしAPIとして`remote=1`を指定した場合、「連合タイムライン」を「リモートのみ」有効にして表示してしまうクライアントアプリがあるかもしれないので、空の配列ではなく`remote=1`を無視してローカル投稿も含む配列を返す
（そういうのはクライアントアプリが悪いのだが、混合されうる場合があると思った）

Change: ローカルタイムラインを無効にしている時、`/api/v1/timelines/public`タイムライン取得で「リモートユーザーのみ」指定も無効化

---

app/lib/activitypub/activity/like.rb
app/lib/vacuum/statuses_vacuum.rb
app/models/emoji_reaction.rb
app/models/favourite.rb
app/models/form/admin_settings.rb
app/views/admin/settings/content_retention/show.html.haml
config/locales/simple_form.en.yml
config/locales/simple_form.ja.yml
config/settings.yml
db/migrate/20240212224800_add_uri_to_favourites.rb
db/migrate/20240212230358_fix_uri_index_to_emoji_reactions.rb
db/schema.rb
lib/tasks/dangerous.rake
spec/controllers/auth/registrations_controller_spec.rb
spec/lib/activitypub/activity/like_spec.rb
spec/lib/vacuum/statuses_vacuum_spec.rb

Add: #518 コンテンツキャッシュについて、リアクションのあった投稿は削除しないオプション

---

db/migrate/20240212230358_fix_uri_index_to_emoji_reactions.rb
db/post_migrate/20240212230358_fix_uri_index_to_emoji_reactions.rb

Fix: #540 emoji_reactionsテーブルのuriカラムへのインデックス設定時、重複を削除する処理

---

app/javascript/mastodon/features/compose/components/privacy_dropdown.jsx

Fix: #531 投稿フォームの公開範囲の選択肢で、スマホから見ると常に「ログインユーザーのみ」が表示される

---

app/javascript/mastodon/features/about/index.jsx

Fix: #554 概要画面の連絡先がメールアドレスでなかった場合に、リンクにmailtoを強制的につけない

---

app/lib/activitypub/activity/create.rb
app/models/admin/ng_word.rb
app/models/form/admin_settings.rb
app/services/activitypub/process_status_update_service.rb
app/services/post_status_service.rb
app/services/update_status_service.rb
app/views/admin/ng_words/show.html.haml
config/locales/en.yml
config/locales/ja.yml
spec/lib/activitypub/activity/create_spec.rb
spec/services/post_status_service_spec.rb

Add: #577 メンション数上限設定を、メンションされた全てのローカルアカウントが相手をフォローしている場合、そうでない場合で分けられるように

---

app/lib/activitypub/activity/create.rb
app/models/admin/ng_word.rb
app/models/ngword_history.rb
app/services/activitypub/process_status_update_service.rb
app/views/admin/ngword_histories/_history.html.haml
db/migrate/20240217022038_add_count_to_ngword_histories.rb
db/schema.rb
lib/tasks/dangerous.rake
spec/lib/activitypub/activity/create_spec.rb

Add: #568 ハッシュタグ・メンション上限を超えた投稿もNGワード履歴に記録

---

app/controllers/admin/accounts_controller.rb
app/helpers/admin/accounts_helper.rb
app/javascript/mastodon/components/visibility_icon.tsx
app/models/account.rb
app/models/account_filter.rb
app/models/form/account_batch.rb
app/policies/account_policy.rb
app/services/activitypub/process_account_service.rb
app/views/admin/accounts/index.html.haml
app/views/admin/ng_words/show.html.haml
app/workers/redownload_avatar_worker.rb
app/workers/redownload_header_worker.rb
config/locales/en.yml
config/locales/ja.yml
db/migrate/20240217093511_add_remote_pending_to_accounts.rb
db/schema.rb
lib/tasks/dangerous.rake
spec/services/activitypub/process_account_service_spec.rb

ホワイトリスト作るならこれも作るべきだと思います
新しいアカウントを認識した時、即時削除せず承認待ち状態にします

Add: ホワイトリスト運用時、承認待ちリモートアカウントの概念ならびに操作画面

---

app/models/form/account_batch.rb

Fix: #596 リモート保留中のアカウントにおいて「活動を完全に停止する」を行ったときも「却下」と同様の動きをするように

---

app/models/user_role.rb
config/roles.yml
spec/models/user_role_spec.rb

標準Mastodonでは、新規登録した管理者以外のユーザーには招待権限が与えられます。しかしこれは以下の理由からセキュリティホールになると考えられます。
- 善人のふりをして登録して、一定時間経過後（例えば管理者が任意のタイミングで登録を承認制にした場合）に大量のスパムを招待を用いて登録する
- 新規登録上限、新規登録可能時間帯、その他のkmyblue独自の制限が迂回可能である
したがって、もしMastodonが初期状態で新規登録を制限するならば、招待も同じく制限されるべきと考えます

Change: 一般ユーザーはデフォルトで招待を不可にするよう変更

---

app/helpers/high_load_helper.rb
app/javascript/mastodon/components/admin/Counter.jsx
app/javascript/mastodon/components/admin/Dimension.jsx
app/javascript/mastodon/locales/en.json
app/javascript/mastodon/locales/ja.json
app/lib/admin/metrics/dimension.rb
app/lib/admin/metrics/measure.rb

これは本来セキュリティインシデントとして起票したものですが、確かに懸念はあるけど秘密裏にやるほど大それたものではないと感じましたので、通常のPRとして起票します。
```
/api/v1/admin/dimensions?keys=[servers]
```
これは、管理者向けダッシュボードでアクティブなサーバーを返すAPIです。
サーバーkmy.blueの場合、このAPI呼び出しから結果が返ってくるまで３分以上かかります。その間に発行されるSQLは１つだけ。AWSのCloudWatchで見ても、データベースディスクの負荷（IOPS）が３分間常にMAXまで張り付いており、繰り返し呼び出すとサーバーが落ちる可能性が高いと考えざるを得ません。例えば悪意を持った者がモデレーターに任命された場合など、モデレーターが気軽にサーバーを落とす／ありえない負荷をかける手段として有効です。
```
/api/v1/admin/measures?keys=[instance_users]
```
これは、既知のサーバーで特定インスタンスの全投稿数を返すAPIです。
サーバーkmy.blueの場合、それほど負荷ではありませんが、過去には１０以上のインスタンス情報を同時表示しただけでデータベースが落ちたこともあり取り扱いには注意が必要なAPIです。
実際の画面において、これらのAPIは遅延的に処理され、呼び出しが完了しなくても次の操作を行うことが出来ます。なので、その遅延処理が高負荷であることに気づきにくく、サーバーを落としやすい要因といえます。
ただ本家Mastodonでは、kmy.blueより圧倒的に大規模なサーバーが大量にあるにかかわらず今までこの問題に対処されていないということは、この問題はkmyblue独自機能に起因する可能性もあるのではないかと思います。その問題の調査を行う前に、いった …

Add: 管理画面で特に負荷の大きい処理を無効にする環境変数

---

app/services/remove_status_service.rb
spec/services/remove_status_service_spec.rb

Fix: #636 投稿削除時エラーが出る場合がある問題

---

app/javascript/mastodon/reducers/compose.js

Fix: #655 センシティブフラグ付きの画像を編集するとフラグが外れる

---

app/javascript/mastodon/actions/compose.js

Change: #671 「メディアを常に閲覧注意としてマークする」をONにしている時、２枚目以降の画像アップロードでセンシティブフラグを付けない

---

app/javascript/mastodon/components/hashtag_bar.tsx
app/javascript/mastodon/features/account/components/header.jsx
app/javascript/mastodon/features/account_timeline/components/header.jsx
app/javascript/mastodon/features/account_timeline/containers/header_container.jsx

Closes #92 
結局、フィールドの上に挿入することにしました

Add: #92 アカウントのおすすめタグを真ん中のカラムからも確認できるように

---

db/post_migrate/20240327234026_fix_duplicate_indices_for_kmyblue_original_functions.rb
db/schema.rb
lib/tasks/dangerous.rake

Fix: #287 DBインデックスの重複の解決

---

app/javascript/mastodon/actions/importer/index.js

Closes #367
Closes #557 
とりあえずJavaScript部分だけ
将来的に、ブーストと動作を合わせる、APIレベルで調整入れるほうがいいと思う

Fix: #367 #557 Webで引用された投稿を表示すると、その投稿のリアクション情報がリセットされる

---

app/models/concerns/account/interactions.rb
app/services/post_status_service.rb
app/services/update_status_service.rb
spec/services/post_status_service_spec.rb

Fix: #703 NGワード、センシティブワード「無関係なフォロワーへのメンション」が、自分自身への参照・引用にも適用される

---

app/javascript/styles/full-dark/diff.scss

フルダークテーマの下記箇所を修正しています。
- `textarea[id='upload-modal__description']`
- 投稿に添付したメディアの編集モーダルウインドウに存在する、「視覚的に閲覧が難しいユーザーへの説明」の入力エリア
- textareaの背景色および文字色が白色のままだったため、視認性が悪かったものを修正しました。
- 修正前：![image](https://github.com/kmycode/mastodon/assets/43964607/04a032f7-7b60-49a5-9e4d-3885593b06f6)
- 修正後：![image](https://github.com/kmycode/mastodon/assets/43964607/5f662297-d93b-4bf8-8d0a-eb8e561ce4c1)
- `.compose-form__warning`
- 投稿画面にて一部の公開範囲などを選んだ際に、入力欄の上部に表示される、注意書き等の表示エリア
- 明るい背景色のため視認性が悪かったものを修正しました
- 修正前：![image](https://github.com/kmycode/mastodon/assets/43964607/de7a644a-7ffa-42c9-b7d1-a4afde60075c)
- 修正後：![image](https://github.com/kmycode/mastodon/assets/43964607/23418590-93e2-450f-ad2c-bd6123cffda8)

Fix: [WebUI] フルダークテーマの修正

---

app/javascript/styles/mastodon/components.scss

Add: #716 スマホで見た時、右サイドメニューの下に大きめの余白

---

app/models/instance_info.rb
spec/models/instance_info_spec.rb

https://kmy.blue/@software/112291229972612270
ごめん普通に現行でも可能だった。当PRはただのリファクタリング以上の意味はないです
> [@emtk](https://kmy.blue/@emtk@mkkey.net) ソフトウェア名が「firefish」となっており独自フォーク名が設定されていないようなのでkmyblue側も現在のプログラムでは対応できませんが、featuresが設定されていればそれを優先するよう修正を検討いたします。
> お時間割いてくださりありがとうございます

Refactor: インスタンスで利用可能な機能を検出する処理

---

app/models/instance_info.rb

Reverts kmycode/mastodon#698
当該実装が`metadata.features`に対応　https://mi.164.one/notes/9s8itn5mzv6r000c
このフォークを利用するサーバーのアップデートを待ちたいのでマージまでに少し期間を置く

Remove: 絵文字リアクション対応サーバーに`rosekey`

---

app/controllers/admin/statuses_controller.rb

Fix: モデレーターが投稿を編集するとき、編集したアカウントを保存する処理においてkmy.blueサーバー向け個別設定を削除
